# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'chart_container.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QSizePolicy, QWidget)

class Ui_chart_container(object):
    def setupUi(self, chart_container):
        if not chart_container.objectName():
            chart_container.setObjectName(u"chart_container")
        chart_container.resize(800, 650)
        chart_container.setMinimumSize(QSize(650, 650))
        chart_container.setStyleSheet(u"\n"
"/* ================================================\n"
"   \u56fe\u8868\u754c\u9762 - \u73b0\u4ee3\u5316\u5de5\u4e1a\u98ce\u683c\n"
"   \u8bbe\u8ba1\u7406\u5ff5\uff1a\u4e13\u4e1a\u3001\u6570\u636e\u53ef\u89c6\u5316\u4f18\u5148\u3001\u6e05\u6670\u5c42\u6b21\n"
"   ================================================ */\n"
"\n"
"/* ========== \u5168\u5c40\u5bb9\u5668 ========== */\n"
"QWidget {\n"
"    font-family: \"Microsoft YaHei\", \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* ========== \u9009\u62e9\u5668\u533a\u57df ========== */\n"
"QLabel {\n"
"    color: #475569;\n"
"    background-color: transparent;\n"
"    padding: 2px 0px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 6px;\n"
"    padding: 7px 12px;\n"
"    background-color: #ffffff;\n"
"    min-height: 20px;\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #94a3b8;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
""
                        "    border-color: #3b82f6;\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    width: 24px;\n"
"    border-left: 1px solid #e2e8f0;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background-color: #f1f5f9;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 5px solid #64748b;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 6px;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #e0e7ff;\n"
"    outline: none;\n"
"    padding: 4px 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 8px 14px;\n"
"    min-height: 18px;\n"
"    color: #334155;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    backgro"
                        "und-color: #f1f5f9;\n"
"}\n"
"\n"
"/* ========== \u4fe1\u606f\u6807\u7b7e ========== */\n"
"QLabel#info_label {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"    padding: 6px 10px;\n"
"    background-color: #f8fafc;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #e2e8f0;\n"
"}\n"
"\n"
"/* ========== \u56fe\u8868\u533a\u57df ========== */\n"
"QChartView {\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"/* ========== \u7edf\u8ba1\u9762\u677f\u5206\u7ec4\u6846 ========== */\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    color: #334155;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 8px;\n"
"    margin-top: 12px;\n"
"    padding-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 12px;\n"
"    padding: 0 8px;\n"
"    color: #3b82f6;\n"
"}\n"
"\n"
"QGroupBox#stats_widget {\n"
"    color: #3b82f6;\n"
"}\n"
"\n"
"/* ========== \u7edf\u8ba1\u8868"
                        "\u683c ========== */\n"
"QTableWidget {\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    background-color: #ffffff;\n"
"    gridline-color: #f1f5f9;\n"
"    selection-background-color: #e0e7ff;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #f8fafc;\n"
"    color: #475569;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #e0e7ff;\n"
"    color: #3730a3;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f8fafc;\n"
"    padding: 10px 8px;\n"
"    border: none;\n"
"    border-bottom: 2px solid #e2e8f0;\n"
"    border-right: 1px solid #f1f5f9;\n"
"    font-weight: 600;\n"
"    color: #475569;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #f1f5f9;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #f8fafc;\n"
"    border: none;\n"
"    border-bottom: 2px solid #e2e8f0;\n"
"}\n"
"\n"
"/* ========== \u6545\u969c"
                        "\u5206\u5e03\u6807\u7b7e ========== */\n"
"QLabel#fault_dist_label {\n"
"    color: #475569;\n"
"    font-size: 11px;\n"
"    padding: 8px 10px;\n"
"    background-color: #f8fafc;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #e2e8f0;\n"
"    line-height: 1.6;\n"
"}\n"
"\n"
"/* ========== \u56fe\u4f8b ========== */\n"
"QLabel#legend_item {\n"
"    color: #475569;\n"
"    font-size: 11px;\n"
"    padding: 4px 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* ========== \u6eda\u52a8\u6761 ========== */\n"
"QScrollBar:vertical {\n"
"    background-color: #f8fafc;\n"
"    width: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #cbd5e1;\n"
"    border-radius: 4px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #94a3b8;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: #"
                        "f8fafc;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #cbd5e1;\n"
"    border-radius: 4px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #94a3b8;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"")

        self.retranslateUi(chart_container)

        QMetaObject.connectSlotsByName(chart_container)
    # setupUi

    def retranslateUi(self, chart_container):
        chart_container.setWindowTitle(QCoreApplication.translate("chart_container", u"\u539f\u59cb\u6570\u636e\u663e\u793a\u56fe", None))
    # retranslateUi

